# Generated by Django 2.1.7 on 2019-03-21 16:59

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=50)),
                ('contributors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=50), size=None)),
                ('iswc', models.CharField(max_length=14)),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.IntegerField()),
            ],
        ),
    ]
