# Generated by Django 2.1.7 on 2019-03-23 16:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import works_single_view.models


class Migration(migrations.Migration):

    dependencies = [
        ('works_single_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='alternate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=works_single_view.models.default_alternate),
        ),
    ]
